const serverConfig = {
    /*
    NIGERIA SERVERS
    */
    '001': { hostname: 'wazobia.live', port: 8333 },
    '002': { hostname: 'webstreaming.viewmedia.tv', port: 443 },
    '003': { hostname: 'africatv.live.net.sa', port: 1937 },
    '004': { hostname: 'tv.ifastekpanel.com', port: 3013 },
    '005': { hostname: 'webstreaming-3.viewmedia.tv', port: 443 },
    '004': { hostname: 'webstreaming-2.viewmedia.tv', port: 443 },
    '007': { hostname: 'webstreaming-7.viewmedia.tv', port: 443 },
    '008': { hostname: 'atechgroupuk.site', port: 443 },
    '009': { hostname: '5d846bfda90fc.streamlock.net', port: 1935 },
    '010': { hostname: 'webstreaming-11.viewmedia.tv', port: 443 },
    '011': { hostname: 'video.servoserver.com.ng', port: 443 },
    '012': { hostname: 'oj7lnn58lg82-hls-live.5centscdn.com', port: 443 },
    '013': { hostname: 'bus-asia-east-1-cimzmgnuu-cdn.sa.metacdn.com', port: 443 },
    '014': { hostname: 'mn-nl.mncdn.com', port: 443 },
    '015': { hostname: 'atechgroupuk.site', port: 443 },
    '016': { hostname: 'media2.streambrothers.com', port: 1936 },
    '017': { hostname: 'mn-nl.mncdn.com', port: 443 },
    '018': { hostname: 'api.visionip.tv', port: 443 },
    '019': { hostname: 'cloud.odysee.live', port: 443 },
    '120': { hostname: '5be80bd118c27.streamlock.net', port: 433 },
    '021': { hostname: '5c0740dba62b3.streamlock.net', port: 443 },
    '022': { hostname: 'acasmedia3.acangroup.org', port: 443 },
    '023': { hostname: 'media2.streambrothers.com', port: 19360 },
    '024': { hostname: 'video1.getstreamhosting.com', port: 1936 },
    '025': { hostname: 'tvce.gridpapaservers.com', port: 443 },
    '026': { hostname: 'newproxy3.vidivu.tv', port: 443 },

    /*
      GHANA SERVERS
    */
    '026': { hostname: 'iptv-trans.ecntv.net', port: 443 },
    '028': { hostname: '1681360479.rsc.cdn77.org', port: 443 },
    '029': { hostname: '5a1178b42cc03.streamlock.net', port: 443 },
    '030': { hostname: 'videodelivery.net', port: 443 },
    '031': { hostname: '59d39900ebfb8.streamlock.net', port: 433 },
    '032': { hostname: 'livetv.tvait.com', port: 1935 },


    /*
      GHANA SERVERS
    */
    '033': { hostname: '', port: 0 },
    '034': { hostname: '', port: 0 },
    '035': { hostname: '', port: 0 },
    '036': { hostname: '', port: 0 },
    '037': { hostname: '', port: 0 },
    '038': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    // Add more mappings for other identifiers as needed
    'default': { hostname: 'default.hostname', port: 8080 },
  };
  
  module.exports = serverConfig;