// config.js
const currentDate = new Date().toUTCString();

const identifierConfig = {
    /*
    NIGERIA SERVERS
    */
    '001': { hostname: 'wazobia.live', port: 8333 , headers: { host: 'wazobia.live', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate } },
    '002': { hostname: 'webstreaming.viewmedia.tv', port: 443 , headers: { host: 'webstreaming.viewmedia.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate } },
    '003': { hostname: 'africatv.live.net.sa', port: 1937 , headers: { host: 'africatv.live.net.sa', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate } },
    '004': { hostname: 'tv.ifastekpanel.com', port: 3013 , headers: { host: 'tv.ifastekpanel.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '005': { hostname: 'webstreaming-3.viewmedia.tv', port: 443 , headers: { host: 'webstreaming-3.viewmedia.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '004': { hostname: 'webstreaming-2.viewmedia.tv', port: 443 , headers: { host: 'webstreaming-2.viewmedia.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '007': { hostname: 'webstreaming-7.viewmedia.tv', port: 443 , headers: { host: 'webstreaming-7.viewmedia.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '008': { hostname: 'atechgroupuk.site', port: 443 , headers: { host: 'atechgroupuk.site', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '009': { hostname: '5d846bfda90fc.streamlock.net', port: 1935 , headers: { host: '5d846bfda90fc.streamlock.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '010': { hostname: 'webstreaming-11.viewmedia.tv', port: 443 , headers: { host: 'webstreaming-11.viewmedia.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '011': { hostname: 'video.servoserver.com.ng', port: 443 , headers: { host: 'video.servoserver.com.ng', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '012': { hostname: 'oj7lnn58lg82-hls-live.5centscdn.com', port: 443 , headers: { host: 'oj7lnn58lg82-hls-live.5centscdn.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '013': { hostname: 'bus-asia-east-1-cimzmgnuu-cdn.sa.metacdn.com', port: 443 , headers: { host: 'bus-asia-east-1-cimzmgnuu-cdn.sa.metacdn.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '014': { hostname: 'mn-nl.mncdn.com', port: 443 , headers: { host: 'mn-nl.mncdn.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '015': { hostname: 'media2.streambrothers.com', port: 1936 , headers: { host: 'media2.streambrothers.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '016': { hostname: 'mn-nl.mncdn.com', port: 443 , headers: { host: 'mn-nl.mncdn.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '017': { hostname: 'api.visionip.tv', port: 443 , headers: { host: 'api.visionip.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '018': { hostname: 'cloud.odysee.live', port: 443 , headers: { host: 'cloud.odysee.live', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '119': { hostname: '5be80bd118c27.streamlock.net', port: 433 , headers: { host: '5be80bd118c27.streamlock.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '020': { hostname: '5c0740dba62b3.streamlock.net', port: 443 , headers: { host: '5c0740dba62b3.streamlock.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '021': { hostname: 'acasmedia3.acangroup.org', port: 443 , headers: { host: 'acasmedia3.acangroup.org', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '022': { hostname: 'media2.streambrothers.com', port: 19360 , headers: { host: 'media2.streambrothers.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '023': { hostname: 'video1.getstreamhosting.com', port: 1936 , headers: { host: 'video1.getstreamhosting.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '024': { hostname: 'tvce.gridpapaservers.com', port: 443 , headers: { host: 'tvce.gridpapaservers.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '025': { hostname: 'newproxy3.vidivu.tv', port: 443 , headers: { host: 'newproxy3.vidivu.tv', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},

    /*
      GHANA SERVERS
    */
    '026': { hostname: 'iptv-trans.ecntv.net', port: 443 , headers: { host: 'iptv-trans.ecntv.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '027': { hostname: '1681360479.rsc.cdn77.org', port: 443 , headers: { host: '1681360479.rsc.cdn77.org', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '028': { hostname: '5a1178b42cc03.streamlock.net', port: 443 , headers: { host: '5a1178b42cc03.streamlock.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '029': { hostname: 'videodelivery.net', port: 443 , headers: { host: 'videodelivery.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '030': { hostname: '59d39900ebfb8.streamlock.net', port: 443 , headers: { host: '59d39900ebfb8.streamlock.net', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},
    '031': { hostname: 'livetv.tvait.com', port: 443 , headers: { host: 'livetv.tvait.com', connection: 'keep-alive', 'sec-ch-ua': '"Not A(Brand";v="99", "Microsoft Edge";v="121", "Chromium";v="121"', 'sec-ch-ua-mobile': '?0', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', 'sec-ch-ua-platform': '"Windows"', accept: '*/*', origin: 'https://livepush.io', 'sec-fetch-site': 'cross-site', 'sec-fetch-mode': 'cors', 'sec-fetch-dest': 'empty', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'if-none-match': '"65b3f985-207"', 'if-modified-since': currentDate }},


    /*
      GHANA SERVERS
    */
    '032': { hostname: 'service-stitcher.clusters.pluto.tv', port: 443, headers: {  'accept': '*/*', 'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'cross-site', 'Referer': 'https://livepush.io/', 'Referrer-Policy': 'strict-origin-when-cross-origin' } },
    '034': { hostname: '', port: 0 },
    '035': { hostname: '', port: 0 },
    '036': { hostname: '', port: 0 },
    '037': { hostname: '', port: 0 },
    '038': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    '': { hostname: '', port: 0 },
    // Add more mappings for other identifiers as needed
    'default': { hostname: 'default.hostname', port: 8080 },
  };
  
  module.exports = identifierConfig;